site_name: SCADR Documentation

nav:
  - Home: index.md
  - Installation: installation.md
  - Modules: modules.md
  - Loading Data: load-data.md
  - Filtering Data: qc.md
  - 1-3D Plot: 13D.md
  - 3D Plot on 2D: 3Don2D.md
  - Correlation Grid and Tests: correlation.md
  - Expression vs Marker Correlation: expressioncorrelation.md
  - tSNE, UMAP, PCA, and Biexponential Transformation: analysisplot.md
  - Licensing and Contribution: contribution.md


theme:
  name: material

