site_name: SCADR Documentation

nav:
  - Home: index.md
  - Installation: installation.md
  - Modules: modules.md
  - Licensing and Contribution: contribution.md
  - Loading Data: load-data.md
  - Quality Control: qc.md
  - 1-3D Plot: 13D.md
  - 3D Plot on 2D: 3Don2D.md
  - Correlation Grid: correlationgrid.md
  - Correlation Tests: correlationtests.md
  - Expression vs Marker Correlation: expressioncorrelation.md
  - tSNE, UMAP, PCA, Biexponentials: analysisplot.md
  - Examples: example.md

theme:
  name: material

