site_name: CellProfilerPlus
site_description: Advanced cell image analysis made simple
site_author: Your Name
repo_url: https://github.com/yourusername/CellProfilerPlus
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Guide: usage.md
  - API Reference: api.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
