name: MATLAB Tests

on:
  push:
    branches: [main, Devs]
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2  # no additional inputs for license

      - name: Run MATLAB tests
        uses: matlab-actions/run-tests@v2
        with:
          use-parallel: true


