name: MATLAB Tests

on:
  push:
    branches: [main, Devs]
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Debug license env
        run: echo "MW_PAT is set = ${{ secrets.MW_PAT != '' }}"

      - name: Check environment
        run: |
          whoami
          echo %TEMP%
          echo %PATH%
          git --version
      
      - name: Setup MATLAB license (login mode)
        uses: mathworks/setup-matlab@v2
        with:
          release: R2026a
          products: MATLAB
        env:
          MLM_LICENSE_MODE: login
          MW_PAT: ${{ secrets.MW_PAT }}
    
      - name: Set MATLAB licensing
        run: |
          echo "MW_PAT=${{ secrets.MW_PAT }}" >> $env:GITHUB_ENV
      
      - name: Activate MATLAB login license
        run: matlab -batch "matlab.internal.activate.activateMATLAB"
        env:
          MW_PAT: ${{ secrets.MW_PAT }}
          
          
      - name: Run tests
        run: matlab -batch "addpath(genpath('Development')); results = runtests('Tests'); exit(~all([results.Passed]));"



