name: MATLAB Tests

on:
  push:
    branches: [main, Devs]
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          access-token: ${{ secrets.MW_PAT }}
      
      - name: Run MATLAB tests
        run: matlab -batch "results = runtests('test'); exit(~all([results.Passed]));"


